options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # SSH into frontend VM and deploy
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh praveenkumar_thati23a@frontend --zone=us-central1-a --command="
          cd ~/taskmaster-frontend &&
          git fetch origin dev &&
          git reset --hard origin/dev &&
          npm install &&
          npm run build &&
          sudo rm -rf /var/www/taskmaster-frontend/* &&
          sudo cp -r build/* /var/www/taskmaster-frontend/ &&
          sudo systemctl reload nginx
        "
